### ISSUE TITLE
I get a broken pipe error when I run aconfmgr save

### ISSUE THREAD

**Issue by chenshuiluke** [CyberShadow/aconfmgr#9] opened 2016-09-19 03:04 UTC
I included all the text in case something useful is in there. You can just skip to the bottom if you want to:

```
aconfmgr save
: Collecting data...
:: Compiling user configuration...
::: Using configuration in /home/luke/.config/aconfmgr
::: Sourcing /home/luke/.config/aconfmgr/99-unsorted.sh...
::: Done (259 native packages, 8 foreign packages, 7490 files).
:: Inspecting system state...
::: Querying package list...
:::: Done.
::: Enumerating managed files...
:::: Done.
::: Searching for lost files...
[sudo] password for luke: 
:::: Warning: reached 1000 lost files while in directory /usr/share/backgrounds/gnome.
::::: Perhaps add IgnorePath /usr/share/backgrounds/gnome/\* (or a parent directory) to configuration to ignore it.
:::: Done (23643 lost files).
::: Searching for modified files...
:::: android-sdk: /opt/android-sdk/tools/NOTICE.txt
:::: android-sdk: /opt/android-sdk/tools/emulator
:::: android-sdk: /opt/android-sdk/tools/emulator64-arm
:::: android-sdk: /opt/android-sdk/tools/emulator64-mips
:::: android-sdk: /opt/android-sdk/tools/emulator64-x86
:::: android-sdk: /opt/android-sdk/tools/lint
:::: android-sdk: /opt/android-sdk/tools/mksdcard
:::: android-sdk: /opt/android-sdk/tools/source.properties
:::: android-sdk: /opt/android-sdk/tools/ant/build.xml
:::: android-sdk: /opt/android-sdk/tools/apps/SdkController/assets/intro_help.html
:::: android-sdk: /opt/android-sdk/tools/apps/SdkController/res/layout/sensors.xml
:::: android-sdk: /opt/android-sdk/tools/lib/ant-tasks.jar
:::: android-sdk: /opt/android-sdk/tools/lib/archquery.jar
:::: android-sdk: /opt/android-sdk/tools/lib/asset-studio.jar
:::: android-sdk: /opt/android-sdk/tools/lib/builder-model.jar
:::: android-sdk: /opt/android-sdk/tools/lib/chimpchat.jar
:::: android-sdk: /opt/android-sdk/tools/lib/common.jar
:::: android-sdk: /opt/android-sdk/tools/lib/ddmlib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/ddms.jar
:::: android-sdk: /opt/android-sdk/tools/lib/ddmuilib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/draw9patch.jar
:::: android-sdk: /opt/android-sdk/tools/lib/dvlib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/emma_device.jar
:::: android-sdk: /opt/android-sdk/tools/lib/fat32lib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/hardware-properties.ini
:::: android-sdk: /opt/android-sdk/tools/lib/hierarchyviewer2.jar
:::: android-sdk: /opt/android-sdk/tools/lib/hierarchyviewer2lib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/jobb.jar
:::: android-sdk: /opt/android-sdk/tools/lib/layoutlib-api.jar
:::: android-sdk: /opt/android-sdk/tools/lib/lint-api.jar
:::: android-sdk: /opt/android-sdk/tools/lib/lint-checks.jar
:::: android-sdk: /opt/android-sdk/tools/lib/lint.jar
:::: android-sdk: /opt/android-sdk/tools/lib/manifest-merger.jar
:::: android-sdk: /opt/android-sdk/tools/lib/monkeyrunner.jar
:::: android-sdk: /opt/android-sdk/tools/lib/ninepatch.jar
:::: android-sdk: /opt/android-sdk/tools/lib/plugin.prop
:::: android-sdk: /opt/android-sdk/tools/lib/rule-api.jar
:::: android-sdk: /opt/android-sdk/tools/lib/screenshot2.jar
:::: android-sdk: /opt/android-sdk/tools/lib/sdk-common.jar
:::: android-sdk: /opt/android-sdk/tools/lib/sdklib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/sdkmanager.jar
:::: android-sdk: /opt/android-sdk/tools/lib/sdkstats.jar
:::: android-sdk: /opt/android-sdk/tools/lib/sdkuilib.jar
:::: android-sdk: /opt/android-sdk/tools/lib/swtmenubar.jar
:::: android-sdk: /opt/android-sdk/tools/lib/traceview.jar
:::: android-sdk: /opt/android-sdk/tools/lib/uiautomatorviewer.jar
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86/libcairo-swt.so
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86/monitor
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86/configuration/config.ini
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86/plugins/com.ibm.icu_4.4.2.v20110823.jar
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86_64/libcairo-swt.so
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86_64/monitor
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86_64/configuration/config.ini
:::: android-sdk: /opt/android-sdk/tools/lib/monitor-x86_64/plugins/com.ibm.icu_4.4.2.v20110823.jar
:::: android-sdk: /opt/android-sdk/tools/lib/pc-bios/bios.bin
:::: android-sdk: /opt/android-sdk/tools/lib/pc-bios/vgabios-cirrus.bin
:::: android-sdk: /opt/android-sdk/tools/proguard/proguard-android-optimize.txt
:::: android-sdk: /opt/android-sdk/tools/proguard/proguard-android.txt
:::: android-sdk: /opt/android-sdk/tools/support/annotations.jar
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/root/res/menu/main.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/root/res/values/dimens.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/root/res/values/strings.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/BlankActivity/root/src/app_package/SimpleActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/FullscreenActivity/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/FullscreenActivity/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/FullscreenActivity/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/activities/FullscreenActivity/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/FullscreenActivity/root/res/layout/activity_fullscreen.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/FullscreenActivity/root/src/app_package/FullscreenActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/root/res/layout/activity_login.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/root/res/values/strings.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/LoginActivity/root/src/app_package/LoginActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/res/layout/activity_content_detail.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/res/layout/activity_content_list.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/res/layout/activity_content_twopane.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/res/layout/fragment_content_detail.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/src/app_package/ContentDetailActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/src/app_package/ContentDetailFragment.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/src/app_package/ContentListActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/MasterDetailFlow/root/src/app_package/ContentListFragment.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/SettingsActivity/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/SettingsActivity/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/SettingsActivity/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/activities/SettingsActivity/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/activities/SettingsActivity/root/src/app_package/SettingsActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/gradle/wrapper/gradle/wrapper/gradle-wrapper.properties
:::: android-sdk: /opt/android-sdk/tools/templates/other/AppWidget/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/AppWidget/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/AppWidget/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/AppWidget/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/AppWidget/root/src/app_package/AppWidget.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/AppWidget/root/src/app_package/AppWidgetConfigureActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/BlankFragment/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/BlankFragment/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/BlankFragment/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/BlankFragment/template_blank_fragment.png
:::: android-sdk: /opt/android-sdk/tools/templates/other/BlankFragment/root/res/layout/fragment_blank.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/BlankFragment/root/src/app_package/BlankFragment.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/BroadcastReceiver/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/BroadcastReceiver/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/ContentProvider/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/ContentProvider/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/CustomView/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/CustomView/root/src/app_package/CustomView.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Daydream/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Daydream/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/Daydream/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Daydream/root/src/app_package/DreamService.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Daydream/root/src/app_package/SettingsActivity.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/IntentService/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/IntentService/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/IntentService/root/AndroidManifest.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/ListFragment/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/ListFragment/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/ListFragment/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/ListFragment/root/res/layout/fragment_grid.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/ListFragment/root/res/layout/fragment_list.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/ListFragment/root/src/app_package/ListFragment.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Notification/recipe.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Notification/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/Notification/root/src/app_package/NotificationHelper.java.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Service/globals.xml.ftl
:::: android-sdk: /opt/android-sdk/tools/templates/other/Service/template.xml
:::: android-sdk: /opt/android-sdk/tools/templates/other/Service/root/AndroidManifest.xml.ftl
:::: bash: /etc/skel/.bashrc
:::: cups: /etc/cups/subscriptions.conf
:::: filesystem: /etc/arch-release
:::: filesystem: /etc/crypttab
:::: filesystem: /etc/fstab
:::: filesystem: /etc/group
:::: filesystem: /etc/gshadow
:::: filesystem: /etc/hosts
:::: filesystem: /etc/passwd
:::: filesystem: /etc/profile
:::: filesystem: /etc/resolv.conf
:::: filesystem: /etc/shadow
:::: filesystem: /etc/shells
:::: filesystem: /usr/lib/os-release
:::: gdm: /etc/gdm/Xsession
:::: gdm: /etc/gdm/custom.conf
:::: glibc: /etc/locale.gen
:::: gnome-backgrounds: /usr/share/gnome-background-properties/gnome-backgrounds.xml
:::: gnome-system-log: /usr/share/help/ja/gnome-system-log/pref-font-size.page
:::: grub: /boot/grub/grub.cfg
:::: grub: /etc/default/grub
:::: linux: /usr/lib/modules/4.7.4-1-ARCH/modules.alias
:::: linux: /usr/lib/modules/4.7.4-1-ARCH/modules.alias.bin
:::: linux: /usr/lib/modules/4.7.4-1-ARCH/modules.dep
:::: linux: /usr/lib/modules/4.7.4-1-ARCH/modules.dep.bin
:::: linux: /usr/lib/modules/4.7.4-1-ARCH/modules.symbols
:::: linux: /usr/lib/modules/4.7.4-1-ARCH/modules.symbols.bin
:::: mkinitcpio: /etc/mkinitcpio.conf
:::: pacman: /etc/pacman.conf
:::: pacman-mirrorlist: /etc/pacman.d/mirrorlist
:::: pam: /etc/environment
:::: playonlinux: /usr/share/playonlinux/etc/playonlinux.png
:::: playonlinux: /usr/share/playonlinux/etc/playonlinux15.png
:::: playonlinux: /usr/share/playonlinux/etc/playonlinux16.png
:::: playonlinux: /usr/share/playonlinux/etc/playonlinux22.png
:::: playonlinux: /usr/share/playonlinux/etc/playonlinux32.png
:::: shadow: /etc/default/useradd
:::: systemd: /etc/systemd/journald.conf
:::: tlp: /etc/default/tlp
:::: vlc: /usr/lib/vlc/plugins/plugins.dat
:::: Done (176 modified files).
::: Reading file attributes...
:::: Reading file types...
[sudo] password for luke: 
/usr/lib/aconfmgr/common.bash: line 929: printf: write error: Broken pipe
:::: Fatal error! Stack trace:
::::: /usr/lib/aconfmgr/common.bash:1 [AconfCompileSystem]
::::: /usr/lib/aconfmgr/common.bash:451 [AconfCompile]
::::: /usr/lib/aconfmgr/save.bash:9 [AconfSave]
::::: /usr/bin/aconfmgr:164 [Main]
::::: /usr/bin/aconfmgr:178 [main]
```

I'm not sure if it's relevant, but i use fish as my shell.

**Comment by CyberShadow** [comment] 2016-09-19 08:10
It's not immediately clear to me why this would happen.

Can you reproduce the problem reliably?

**Comment by CyberShadow** [comment] 2016-09-19 21:23
I am unable to reproduce this problem.

I would suggest to try ignoring files and directories that you don't want to be considered part of the system configuration, as instructed, to bring the total file count down from the current 23643 to under 1000 files.

In theory, the problem could occur if some files were present during the initial lost files scan, but became absent during the attribute collection. This can happen if a process is creating and deleting files during aconfmgr's run.

**Comment by CyberShadow** [comment] 2017-03-06 23:41
Seeing as there are no actionable points from this side, and no feedback for 5 months, closing.

**Closed by CyberShadow** 2017-03-06 23:41 UTC
